services:
  q1-app:
    image: q1-app:latest
    hostname: q1
    build:
      context: ./services/q1/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      QUARKUS_HTTP_PORT: 8080
    stdin_open: true
    tty: true
    networks:
      - "app-network"
  q2-app:
    image: q2-app:latest
    hostname: q2
    build:
      context: ./services/q2/
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8088:8080"
    environment:
      QUARKUS_HTTP_PORT: 8080
    stdin_open: true
    tty: true
    networks:
      - "app-network"
networks:
  app-network:
    driver: bridge
