# MongoDB connection settings
quarkus:
  mongodb:
    connection-string: "mongodb://host.docker.internal:27017"
    database: "game-reviews"

    # Optional: Credentials (if MongoDB has auth enabled)
#    credentials:
#      username: "admin"
#      password: "secret"
